version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: bruin-windows-amd64
    binary: bruin
    main: ./
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}"
    flags:
      - -trimpath
      - -buildmode=exe

archives:
  - format: tar.gz
    builds:
      - bruin-windows-amd64
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"



