name: bruin-init
schedule: "@daily"
start_date: "2023-03-20"

default_connections:
  google_cloud_platform: "alberto_gcp"
  snowflake: "snowflake"
  postgres: "postgres"
  mssql: "mssql"
  synapse: "synapse"
  mongo: "mongo"
  mysql: "some_mysql"
  notion: "some_notion"
  hana: "some_hana"
  shopify: "some_shopify"
  gorgias: "some_gorgias"
  aws: "my_aws"
  klaviyo: "my_klaviyo"
  adjust: "my_adjust"
  facebookads: "my_facebookads"
  stripe: "my_stripe"
  appsflyer: "my_appsflyer"
  kafka: "my_kafka"
  hubspot: "my_hubspot"
  googlesheets: "my_gsheets"
  chess: "my_chess"
  airtable: "my_airtable"
  s3: "my_s3"
  slack: "my_slack"
  zendesk : "my_zendesk"
