default_environment: default
environments:
  default:
    connections:
#      postgres:
#        - name: "example-postgres"
#          username: "some-username"
#          password: "some-password"
#          host: "some-host.postgresql.provider.net"
#          port: 5432
#          database: "some-database"
#          schema: "public"
      google_cloud_platform: []
      redshift: []
      generic: []
      mssql: []
      synapse: []
